import { LotType } from '@/type/lots.type';

export const LOT_DEFAULT: LotType = {
  lotId: '',
  lotName: '',
  skinType: '',
  billetType: '',
  customerName: '',
  start: new Date(),
  end: new Date(),
  dyNumber: '',
  dyScreen: '',
  dySkin: '',
  billetScreen: '',
  billetMiddle: '',
  container: '',
  boNo: '',
  insNo: '',
  holeCount: '',
  averageWeight: '',
  billetWeight: '',
  factoryDate: new Date(),
  billetNumber: '',
  ironingSize: '',
  tendon: '',
  billetCount: '',
  times: '',
  longShop: '',
  longExpect: '',
  good: '',
  waste: '',
  wastePercent: '',
  speedPull: '',
  desc: '',
};
