export type LotType = {
  lotId: string;
  lotName: string;
  skinType: string;
  billetType: string;
  customerName: string;
  start: Date | null;
  end: Date | null;
  dyNumber: string;
  dyScreen: string;
  dySkin: string;
  billetScreen: string;
  billetMiddle: string;
  container: string;
  boNo: string;
  insNo: string;
  holeCount: string;
  averageWeight: string;
  billetWeight: string;
  factoryDate: Date | null;
  billetNumber: string;
  ironingSize: string;
  tendon: string;
  billetCount: string;
  times: string;
  longShop: string;
  longExpect: string;
  good: string;
  waste: string;
  wastePercent: string;
  speedPull: string;
  desc: string;
};
