services:
  prod:
    container_name: metro-report-web
    image: metro/report/report-web
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 31032:3000
    restart: unless-stopped
